### ISSUE TITLE
8 digits precision instead of 6.

### ISSUE THREAD

**Issue by marcopax** [alecananian/osx-coin-ticker#10]
Hi, good work with the application, but working with altcoin make it useless.
An alt coin can have a value very low: since the application only displays 6 digit after the comma, the value is always rounded.

Example:
ADA value is currently 0,00005956 -> Application shows 0,00006

Is it possible to configure number of digit in order to choose it? It would be perfect to display only the satoshi number (so in case of ADA 5956) instead the entire part with "0,0000".

**Comment by alecananian** [comment]
Yep, that's a great idea - I will display the satoshi number when the value falls that far below 1.0

**Comment by alecananian** [comment]
@marcopax How does this look?

<img width="438" alt="satoshi" src="https://user-images.githubusercontent.com/1013230/34708384-449b2622-f4c7-11e7-93fc-7296f98518f0.png">

If the price is less that 0.001 BTC, I'll use satoshi instead. For other currencies, I'll show additional fraction digits so there are always four digits after the first significant one.

**Comment by marcopax** [comment]
Seems perfect: so for coins with low value only satoshi value is shown (so the second one, "ADA 5,892 sat").
It helps a lot, thank you :)

**Comment by kedem** [comment]
![screen shot 2018-01-11 at 13 37 44](https://user-images.githubusercontent.com/5393447/34825897-a90e9a26-f6d4-11e7-998e-8936dd5f48a7.png)
My app still shows 6 digits :(

**Comment by alecananian** [comment]
Hi @kedem, the update is still pending Apple approval.  I expect it to be approved today.

**Comment by alecananian** [comment]
Done in [v2.1.0](https://github.com/alecananian/osx-coin-ticker/releases/tag/v2.1.0) and now available in the App Store
