### ISSUE TITLE
Add Binance exchange

### ISSUE THREAD

**Issue by lucasren** [alecananian/osx-coin-ticker#15]
Hi thank you for your update, the multiple currency display is very nice!

I'd like to point out there is an amazing exchange called Binance that is capturing all the trading volume right now and has become top 1 worldwide exchange in just 6 months.
You should implement their alts/ETH alts/BTC trading pairs :)

Thanks

**Comment by alecananian** [comment]
Thanks for the kind words!
Check your app again - Binance (issue #9) was implemented in v2.0.0 😄

**Comment by lucasren** [comment]
ho I didnt notice, thanks ! ˆˆ
