### ISSUE TITLE
Kraken Market is not working since their infra upgrade

### ISSUE THREAD

**Issue by dreamingthink** [alecananian/osx-coin-ticker#16]
Hello,

Kraken has recently upgraded his infrastructure.
I'm not able to see the currency value instead they are Cointicket logo.

Could you check ?

P.S : Your app is great !

**Comment by alecananian** [comment]
@dreamingthink are you still having issues with this?  The Kraken website and API were completely down while they were upgrading, so that was causing the error.  The API is back up now, and it appears to be unchanged, so I'm not seeing any issues.

**Comment by dreamingthink** [comment]
Hello,

Yes I still have the issue. Is there a config file I need to remove ?

**Comment by alecananian** [comment]
@dreamingthink Yes, please try switching to a different exchange and then back to Kraken. Or try quitting the Cointicker app and restarting it. Thanks.

**Comment by dreamingthink** [comment]
Hello, 
I have already tried to switching a different exchange (I can see values) but when i come back to Kraken, i have the "ct" logo.
I have also tried to uninstall & reinstall the app.

**Comment by alecananian** [comment]
@dreamingthink okay thanks for trying all these things out.  The last thing you could try is hitting the Kraken API in your browser to see if it's down in your region: https://api.kraken.com/0/public/AssetPairs

The Kraken status page (https://status.kraken.com) shows API as "Degraded Performance".  When it's back to "Operational" I'll have you try it out again 🙂  In the meantime, I'll keep checking to see if there are any issues on my end.

**Comment by dreamingthink** [comment]
Hello,
Thank you.
I have tried with my browser. The URL is working. I have attached a video to my issue.
[screen.m4v.zip](https://github.com/alecananian/osx-coin-ticker/files/1628610/screen.m4v.zip)

**Comment by dreamingthink** [comment]
Hello,

I have solved my issue by removing the following folder :
/Users/<MyUser>/Library/Containers/com.alecananian.cointicker/Data/Library/Caches

Thank you

**Comment by alecananian** [comment]
Glad you resolved it, and thanks for the tip.  I'll see if I can clear out that cache on launch.
