### ISSUE TITLE
bigsur support

### ISSUE THREAD

**Issue by mohamedsharaf** [alecananian/osx-coin-ticker#27]
bigsur is not supported

**Comment by alecananian** [comment]
@mohamedsharaf Can you please provide some more detail about what is not working for you on Big Sur? Are you attempting to run the source from Xcode or have you downloaded it from the App Store? I'm on macOS 11.0.1 and have not encountered any issues so far.

**Comment by alecananian** [comment]
Closing due to lack of issue details
