### ISSUE TITLE
Support for STRONG token

### ISSUE THREAD

**Issue by karlpablo** [alecananian/osx-coin-ticker#28]
Price for STRONG token simply shows up as "$?".

The token address is 0x990f341946a3fdb507ae7e52d17851b87168017c from https://strongblock.com/.

**Comment by alecananian** [comment]
@karlpablo which exchange are you using to view that token?

**Comment by karlpablo** [comment]
KuCoin

**Comment by alecananian** [comment]
@karlpablo I'm seeing an issue with Gate.io not loading properly, but KuCoin looks fine to me. Can you please provide a screenshot?

**Comment by karlpablo** [comment]
![image](https://user-images.githubusercontent.com/1310060/149451982-8e240f14-56ea-49de-b316-e1c2625090d8.png)

**Comment by alecananian** [comment]
@karlpablo sorry, but that is a different application. This code repository is for [CoinTicker](https://apps.apple.com/us/app/cointicker-bitcoin-and-ethereum-ticker/id1247300730).
