### ISSUE TITLE
Allow multiple coin prices to be displayed at once in menu bar

### ISSUE THREAD

**Issue by alecananian** [alecananian/osx-coin-ticker#6]
Currently the app only supports showing one coin price at a time in the menu bar.  Instead, it should allow the user to select multiple coins to be displayed at once.

**Comment by Niek** [comment]
+1 on this. The [Coin Tick app](http://yoni.ninja/cointick) does the same.

**Comment by schallertd** [comment]
+1 for selecting multiple coins in the menubar,  but also showing prices within the dropdown menu (like cointick) would be awesome:

![cointick](https://user-images.githubusercontent.com/26160366/29545864-19c71fbc-86f1-11e7-9ced-9e2d849f205e.png)

**Comment by Emond999** [comment]
+1, the EUR rates are well synchronized with the exchanges, it's what I was looking for primarily.
With multiple coins support and an option to start at launch, the app will be perfect for me

**Comment by tomillo** [comment]
+1

**Comment by vietquocnguyen** [comment]
+1

**Comment by caniyabanci76** [comment]
+1

**Comment by donbeave** [comment]
+1

**Comment by alecananian** [comment]
Done in [v2.0.0](https://github.com/alecananian/osx-coin-ticker/releases/tag/v2.0.0)
