### ISSUE TITLE
Kraken: get latest trade price, not last 24h price

### ISSUE THREAD

**Issue by Niek** [alecananian/osx-coin-ticker#7]
See this code:
https://github.com/alecananian/osx-coin-ticker/blob/63e82605dd7e9e672c2446500c128170bad951f1/CoinTicker/Source/Exchanges/KrakenExchange.swift#L70-L72

Compare to the API docs: https://www.kraken.com/help/api#get-ticker-info

Right now you use the volume weighted average price of last 24h. Better would be to use the last trade closed. So the first value of the ``c`` array.

**Comment by alecananian** [comment]
Fixed in [v1.2.1](https://github.com/alecananian/osx-coin-ticker/releases/tag/v1.2.1)
