### ISSUE TITLE
Support of Bitcoin Cash (BCH)

### ISSUE THREAD

**Issue by dreamingthink** [alecananian/osx-coin-ticker#8]
Hello,

Is it possible to add a support of Bitcoin Cash. It is available on Kraken.

Thank you

**Comment by alecananian** [comment]
Thanks for the feedback! Bitcoin Cash support has been made available in [v1.2.2](https://github.com/alecananian/osx-coin-ticker/releases/tag/v1.2.2) which should be rolling out to the App Store soon.
