### ISSUE TITLE
Add Binance Exchange

### ISSUE THREAD

**Issue by alecananian** [alecananian/osx-coin-ticker#9]

**Comment by pionl** [comment]
With this feature it would be great to add support full list from binance 👍

**Comment by alecananian** [comment]
Done in [v2.0.0](https://github.com/alecananian/osx-coin-ticker/releases/tag/v2.0.0)

@pionl, the change also came with a bunch of newly supported altcoins.  Please let me know if there are any missing that you'd like to follow and I can add them.

**Comment by pionl** [comment]
Thanks! I have all I need. Just bought the App Store version and found that IOTA is missing title (Czech translation). 

Also I'm using Binance, but I would like to see also BTC price in USD (I don't care which exchange). Don't see the option to do this.

**Comment by alecananian** [comment]
Thanks for your support! IOTA translation will be fixed in the next version, coming soon.

As for showing prices in USD, the app currently only supports this if the exchange does.  The exchange API provides a list of supported trading markets, which is how the main menu gets built.  There are ways I could provide this, by grabbing the BTC price then converting using the BTC-USDT value, but I've avoided calculating currency conversions on my own because I'd prefer to only display the exact values that the exchange offers.  However, I can look into it to see how accurate the values I get are.  If you could create a new issue, that'd be best. Thanks again!
